//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kasthack.ApostlePeter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kasthack.ApostlePeter.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не надо пытаться накормить меня картинками или голосовухами. Цивилизованный AI понимает только текст..
        /// </summary>
        internal static string AIOnlyUnderstandsText {
            get {
                return ResourceManager.GetString("AIOnlyUnderstandsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всё развалилось при попытке отрезолвить ссылку {0}: {1}.\n\n Попробуйте позже.
        /// </summary>
        internal static string ErrorWhileProcessingProfile {
            get {
                return ResourceManager.GetString("ErrorWhileProcessingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всё развалилось при попытке проверить аккаунт {0}. Если у вас приватный профиль, это могло быть причиной.: {1}.
        /// </summary>
        internal static string ErrorWhileProcessingProfileV2 {
            get {
                return ResourceManager.GetString("ErrorWhileProcessingProfileV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено {0} террористических постов и {1} групп..
        /// </summary>
        internal static string FoundNPostsAndMGroups {
            get {
                return ResourceManager.GetString("FoundNPostsAndMGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет, мой маленький экстремист(ка). Отправь мне ссылку на страницу ВК, по которой нужны рекомендации по очистке.\n\nРепорты о проблемах / запрос фич можно отправить сюда: https://t.me/joinchat/LCYlmetoVigzODQ6.
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группы:.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я ничего не нашёл, но, возможно, ФСБ сумеет. Если у вас закрытый профиль, это могло быть причиной..
        /// </summary>
        internal static string IHaventFoundAnything {
            get {
                return ResourceManager.GetString("IHaventFoundAnything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домен {0} не похож на vk.com..
        /// </summary>
        internal static string InvalidDomain {
            get {
                return ResourceManager.GetString("InvalidDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это не похоже на ссылку на профиль вк. Обычно та выглядит как &apos;https://vk.com/id1&apos; или &apos;https://vk.com/durov&apos;.
        /// </summary>
        internal static string InvalidProfileLink {
            get {
                return ResourceManager.GetString("InvalidProfileLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это(&apos;{0}&apos;) совсем не похоже на ссылку. @&lt;username&gt; не поддерживаются, используйте https://vk.com/&lt;username&gt;.
        /// </summary>
        internal static string InvalidUri {
            get {
                return ResourceManager.GetString("InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Репорт в JSON для нердов.
        /// </summary>
        internal static string JsonReportForNerds {
            get {
                return ResourceManager.GetString("JsonReportForNerds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это не профиль ВК. Группы пока не обрабатываются(делаю). Обычно ссылка выглядит как &apos;https://vk.com/id1&apos; или &apos;https://vk.com/durov&apos;.
        /// </summary>
        internal static string NotAVkProfile {
            get {
                return ResourceManager.GetString("NotAVkProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посты:.
        /// </summary>
        internal static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: перепроверяйте за мной. Я могу не определить какие-то упоминания. Если вы нашли пропущенный пост/группу, напишите об этом в чат разработки бота -- автор поправит.
        ///
        ///.
        /// </summary>
        internal static string RecheckManuallyWarning {
            get {
                return ResourceManager.GetString("RecheckManuallyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Думаем... Пока использую один токен на всех пользователей, так что, возможно, это надолго.
        /// </summary>
        internal static string Thinking {
            get {
                return ResourceManager.GetString("Thinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тут лет на 20 наберется..
        /// </summary>
        internal static string YouAreGoingToJailForTwentyYears {
            get {
                return ResourceManager.GetString("YouAreGoingToJailForTwentyYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Похоже, у вас приватный профиль. Поменяйте настройки приватности..
        /// </summary>
        internal static string YourProfileIsPrivate {
            get {
                return ResourceManager.GetString("YourProfileIsPrivate", resourceCulture);
            }
        }
    }
}
